version: '3.7'
services:
  app-nodejs:
    image: app-nodejs
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=root
      - MONGO_PASSWORD=teste
  mongodb:
    image: mongo
    hostname: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=teste
